#!/usr/bin/env python3
"""
JIS0208.TXT から SJIS→Unicode 変換表を生成する。

入力:  /tmp/jis0208.txt   (Unicode.org 公式の JIS0208.TXT)
出力:  source/sjis_table.h

テーブル構造:
    static const uint16_t SJIS_TO_UNI[60][188] = { ... };

インデックス:
    lead  (0..59):  0x81-0x9F → 0..30, 0xE0-0xFC → 31..59
    trail (0..187): 0x40-0x7E → 0..62, 0x80-0xFC → 63..187
    値 0 は「未割当」
"""
import sys

ROWS = 60
COLS = 188

def lead_bucket(c):
    if 0x81 <= c <= 0x9F: return c - 0x81
    if 0xE0 <= c <= 0xFC: return c - 0xE0 + 31
    return None

def trail_bucket(c):
    if 0x40 <= c <= 0x7E: return c - 0x40
    if 0x80 <= c <= 0xFC: return c - 0x80 + 63
    return None

def main():
    table = [[0] * COLS for _ in range(ROWS)]
    count = 0
    skipped = 0
    with open('tools/JIS0208.TXT', 'r', encoding='utf-8') as f:
        for line in f:
            if line.startswith('#'): continue
            parts = line.split()
            if len(parts) < 3: continue
            try:
                sjis = int(parts[0], 16)
                uni  = int(parts[2], 16)
            except ValueError:
                continue
            c1 = (sjis >> 8) & 0xFF
            c2 = sjis & 0xFF
            lb = lead_bucket(c1)
            tb = trail_bucket(c2)
            if lb is None or tb is None:
                skipped += 1
                continue
            if uni > 0xFFFF:
                # BMP 外: 今回は無視 (JIS X 0208 にはほぼ無い)
                skipped += 1
                continue
            table[lb][tb] = uni
            count += 1

    out = []
    out.append('// AUTO-GENERATED by tools/gen_sjis_table.py - DO NOT EDIT BY HAND\n')
    out.append('// Source: unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT\n')
    out.append(f'// Mapped: {count} codepoints, skipped: {skipped}\n')
    out.append('#pragma once\n')
    out.append('#include <cstdint>\n\n')
    out.append('namespace sjis_table {\n\n')
    out.append('// Index: [lead_bucket][trail_bucket]\n')
    out.append('//   lead_bucket(c):  0x81-0x9F -> 0..30,  0xE0-0xFC -> 31..59\n')
    out.append('//   trail_bucket(c): 0x40-0x7E -> 0..62,  0x80-0xFC -> 63..187\n')
    out.append('// Value 0 means unmapped.\n')
    out.append(f'static constexpr int ROWS = {ROWS};\n')
    out.append(f'static constexpr int COLS = {COLS};\n\n')
    out.append(f'static const uint16_t TABLE[{ROWS}][{COLS}] = {{\n')
    for r in range(ROWS):
        row_vals = table[r]
        out.append('    { ')
        for i, v in enumerate(row_vals):
            out.append(f'0x{v:04X}')
            if i + 1 < COLS:
                out.append(',')
            if (i + 1) % 12 == 0 and i + 1 < COLS:
                out.append('\n      ')
            else:
                out.append(' ')
        out.append('},\n')
    out.append('};\n\n')
    out.append('} // namespace sjis_table\n')

    with open('source/sjis_table.h', 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(out))
    print(f'generated source/sjis_table.h: {count} mapped, {skipped} skipped')

if __name__ == '__main__':
    main()
